package com.ltalk.server.enums;

public enum ProtocolType {
    CHAT, SIGNUP, LOGIN, CHAT_LIST, DISCONNECT, REQUEST_FRIEND, CREATE_CHATROOM,
    NEW_CHAT, READ_CHAT, GET_VOICE_SERVER_IP, JOIN_VOICE_CHAT, RESPONSE_CREATE_CHATROOM_MEMBER,
    FRIEND_SEARCH, CONNECT_VOICE_SERVER, CRATE_VOICE_SERVER, CAN_CREATE_CHAT_ROOM,
    CHATROOM_LIST;
}
