package com.ltalk.server.enums;

public enum ProtocolType {
    CHAT, SIGNUP, LOGIN, CHAT_LIST, DISCONNECT, REQUEST_FRIEND, CREATE_CHATROOM, NEW_CHAT, READ_CHAT, CRATE_VOICE_SERVER, CONNECT_VOICE_SERVER, GET_VOICE_SERVER_IP, JOIN_VOICE_CHAT, RESPONSE_CREATE_CHATROOM_MEMBER;
}
